name: referme
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  lottie: ^3.1.2
  device_preview: ^1.1.0
  auto_size_text: ^3.0.0
  flutter_contacts: ^1.1.9+2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.2.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - resources/images/
    - lib/utils/card_list.json

  fonts:
    - family: Poppins
      fonts:
        - asset: resources/fonts/Poppins-Black.ttf
          weight: 900
        - asset: resources/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: resources/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: resources/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: resources/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: resources/fonts/Poppins-Light.ttf
          weight: 300
        - asset: resources/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: resources/fonts/Poppins-Thin.ttf
          weight: 100

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
